server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/zomato-realm}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

logging:
  level:
    org.springframework.cloud.gateway.server.mvc: TRACE
    org.springframework.security: DEBUG
