server:
  port: 8083

spring:
  application:
    name: search-service
  elasticsearch:
    uris: ${SEARCH_ENDPOINT:${ELASTICSEARCH_URL:http://localhost:9200}}
    username: ${SEARCH_USERNAME:}
    password: ${SEARCH_PASSWORD:}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
