server:
  port: 8084

spring:
  application:
    name: location-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Map API Configurations (e.g., Google Maps, Mapbox)
map:
  api:
    key: ${MAP_API_KEY:default_key}
