name: Deploy Backend to Oracle Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'docker/docker-compose.prod.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Oracle Cloud VM via SSH Action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_HOST_IP }}
          username: ubuntu
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd Zomato_UC
            git pull origin main
            docker-compose -f docker/docker-compose.prod.yml up -d --build
